### ISSUE TITLE
error processing RDML files exported from BioRad CFX Maestro software

### ISSUE THREAD

**Issue by JackieMium** [PCRuniversum/RDML#27]
We've got two qPCR instruments in our lab, one is CFX Connect and the computer has Bio-Rad CFX Manager 3.0 installed, the other is CFX96Touch and computer has CFX Maestro 1.1 software. Both software produces `xxxxx.pcrd` as results by default and support export to rdml v1.1 format. For data import and processing, I am following [the supplements SI1.pdf of your paper](https://doi.org/10.1093/bioinformatics/btx528) (BTW, link in README here to https://kablag.github.io/RDML/ seems dead and I cannot find it anywhere else, donno if the manual has been updated and I was maybe following an outdated version or what). 

Commands I used to import my results:

```R
raw_data <- RDML$new("/path/to/rdml")
fdata <- raw_data$GetFData(dplyr::filter(raw_data_tab, sample.type == "unkn"), long.table = FALSE)
```

Problem is, if I'am importing a file exported from CFX Manager, I get the `fdata` with no error, while if the file was exported from CFX Maestro, the `raw_data$GetFData()` step always says:

```
Error: Assertion failed. One of the following must apply:
 * checkClass(out): Must inherit from class 'adpsType', but has class 'NULL'
 * checkClass(out): Must inherit from class 'mdpsType', but has class 'NULL'
```

I tried to export rdml v1.0 but in vain. Also, I noticed that CFX Manager failed to open results produced from CFX96Touch & CFX Maestro, while CFX Maestro was able to open files from 
CFX96Touch & CFX Maestro and CFX Connect & CFX Manager, although they were all `xxxx.pcrd` files (maybe due to software compatibility issues?)

**Comment by kablag** [comment]
> link in README here to https://kablag.github.io/RDML/ seems dead and I cannot find it anywhere else

now it is here https://pcruniversum.github.io/RDML/

> Problem is, if I'am importing a file exported from CFX Manager, I get the fdata with no error, while if the file was exported from CFX Maestro, the raw_data$GetFData() step always says:

I don't have CFX Maestro now. So please attach your rdml and pcrd files.

> Also, I noticed that CFX Manager failed to open results produced from CFX96Touch & CFX Maestro, while CFX Maestro was able to open files from
CFX96Touch & CFX Maestro and CFX Connect & CFX Manager, although they were all xxxx.pcrd files (maybe due to software compatibility issues?)

CFX Maestro somehow change file from CFX Manager that it can't be open in CFX Manager after saving. That's why I don't use CFX Maestro anymore… Small improvements in statistical analysis don't worth it.

**Comment by JackieMium** [comment]
> 
> now it is here https://pcruniversum.github.io/RDML/
> 

No, I mean the link to Manual in README is dead, https://kablag.github.io/RDML/. The Manual Section at https://pcruniversum.github.io/RDML/ also points to https://kablag.github.io/RDML/ which is dead link.

>
> I don't have CFX Maestro now. So please attach your rdml and pcrd files.
>

Here is a rmdl v1.1 and pcrd file from Maestro: 

[Maestro.zip](https://github.com/PCRuniversum/RDML/files/4043618/Maestro.zip)

It was one of my runs performed by CFX96Touch, result was produced from Maestro and rmdl exprted from Maestro too. The pcrd file cannot be opened by  CFX Manager and the `GetFData()` failed with errors mentioned above.

> 
> CFX Maestro somehow change file from CFX Manager that it can't be open in CFX Manager after saving. That's why I don't use CFX Maestro anymore… Small improvements in statistical analysis don't worth it.
>

This is something I cannot decide as the two instruments are owned by the lab and I don't get to installed/uninstall softwares on the computers attched to them.

Thanks.

**Comment by kablag** [comment]
> No, I mean the link to Manual in README is dead, https://kablag.github.io/RDML/. The Manual Section at https://pcruniversum.github.io/RDML/ also points to https://kablag.github.io/RDML/.

Corrected.

> It was one of my runs performed by CFX96Touch, result was produced from Maestro and rdml exported from Maestro too. The pcrd file cannot be opened by CFX Manager and the GetFData() step failed with errors mentioned above.

I looked at RDML file generated by Maestro and it does not contain any fluorescence points at all:
`<react id="56"><sample id="group4" /><data><tar id="Actin" /><cq>16.1183718203916</cq></data></react>`
only Cq. So I can't correct this. Maybe Maestro contain some export options? Or try to export in different RDML format versions and send to me generated files.

**Comment by JackieMium** [comment]
> 
> I looked at RDML file generated by Maestro and it does not contain any fluorescence points at all:
> `<react id="56"><sample id="group4" /><data><tar id="Actin" /><cq>16.1183718203916</cq></data></react>`
> only Cq. So I can't correct this. Maybe Maestro contain some export options? Or try to export in different RDML format versions and send to me generated files.

Unfortunately there aren't any options in setting regarding exporting to RDML except to v1.0 or v1.1. Anyway I export the same file to RDML v1.0 and here it is(it's actually not a zip file, just change `.zip` to `.rdml`):

[Maestro.v1.0.zip](https://github.com/PCRuniversum/RDML/files/4045363/Maestro.v1.0.zip)

In Maestro, if you try the "Custom Export" there will be options regarding what to include in the output files, but RDML is not supported in custom export. Anyway, I chose to export anything I see into a XML file and here it is(again it's actually not a zip file, just remove `.zip`):

[Maestro.xml.zip](https://github.com/PCRuniversum/RDML/files/4045381/Maestro.xml.zip)

**Comment by kablag** [comment]
> Anyway I export the same file to RDML v1.0 and here it is

It does not contain fluorescence points too…
Maybe you have to make some PCR analysis inside Maestro, then save file and export? For example ABI7500 adds data after analysis.

Another option is ask Biorad about this issue.

**Comment by JackieMium** [comment]
> It does not contain fluorescence points too…
> Maybe you have to make some PCR analysis inside Maestro, then save file and export? For example ABI7500 adds data after analysis.
>

Well, I've already done some analysis, this is a plot for gene2 expression relative to NC group:

![image](https://user-images.githubusercontent.com/12944832/72160102-bc2a0d80-33f8-11ea-9c7d-8b240acf28fa.png)

> 
> Another option is ask Biorad about this issue.

I'll try to contact BioRad for this.

Thank you @kablag for your paitence and advice.

**Comment by kablag** [comment]
> I'll try to contact BioRad for this.

keep me in touch please if they answer you

**Comment by JackieMium** [comment]
@kablag I will. But they don't seem to reply to my email feedbacks.

_Sent from my ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
