### ISSUE TITLE
RDML$new assertion error NA

### ISSUE THREAD

**Issue by prhutchi** [PCRuniversum/RDML#28]
I need to import uncorrected fluorescence data (no baseline subtraction and thus no software curve analysis) into R from an RDML file. When working in R with the RDML package and trying to import default RDML output from BioRad CFX Maestro v1.1 software I consistently run into the following error:

`Error in (function (cq)  : Assertion on 'cq' failed: May not be NA.`

The import terminates at this error and no object is created. I understand that the function is unhappy about NA values in the cq but I don't know how to solve this issue to work with the data in R. This error also occurs when using RDMLedit online.

I am attaching an RDML output by Maestro (salmonid_ef1a.rdml) which fails with the above error. How can I get these Maestro files into R to work with the fluorescence data?

[salmonid_ef1a.zip](https://github.com/PCRuniversum/RDML/files/7499435/salmonid_ef1a.zip)

**Comment by kablag** [comment]
Unfortunately I don't have biorad maestro, but I'll try to look into your data and to understand problem

**Comment by kablag** [comment]
I looked inside your file (you can do this by renaming rdml to zip) - it doesn't have any fluorescence or Cq information inside. So it's not RDML package problem...
Below is a screenshot of your file content
![image](https://user-images.githubusercontent.com/1788726/141081350-ea5c4317-cdb9-4019-a20b-bb61904da533.png)

Here is the correct one
![image](https://user-images.githubusercontent.com/1788726/141082063-474af7c5-0a68-461a-9db8-4e942afc5a6f.png)
