### ISSUE TITLE
RDML$new assertion error NA

### ISSUE THREAD

**Issue by epruesse** [PCRuniversum/RDML#34]
I am getting the same assertion violation as described in #28:

```R
Error in (function (cq)  : Assertion on 'cq' failed: May not be NA.
```

The RDML should parse OK. As you can see below, the `<cq>NaN</cq>` tag appears legitimately when a reaction did not amplify at all (e.g. a negative test). 

```XML
[...]
            <react id="1">
                <sample id="mysample1"/>
                <data>
                    <tar id="the_target"/>
                    <cq>NaN</cq>
                    <adp>
                        <cyc>1.0</cyc>
                        <fluor>0.045274403</fluor>
                    </adp>                    
[...]
                    <adp>
                        <cyc>45.0</cyc>
                        <fluor>-0.013826137</fluor>
                    </adp>
[...]
            <react id="86">
                <sample id="mysample1"/>
                <data>
                    <tar id="the_positive_control"/>
                    <cq>26.96937</cq>
                    <adp>
                        <cyc>1.0</cyc>
                        <fluor>0.01319422</fluor>
                    </adp>
[...]
                    <adp>
                        <cyc>25.0</cyc>
                        <fluor>0.090496756</fluor>
                    </adp>
                    <adp>
                        <cyc>26.0</cyc>
                        <fluor>0.13862325</fluor>
                    </adp>

```

**Comment by kablag** [comment]
As I mention in #28  this is not RDML package problem because it is standard violation
![image](https://user-images.githubusercontent.com/1788726/173789221-946c34fd-9ae1-4ecb-b54d-1c1675735ce6.png)
You can see that Cq can't be NaN. For NA case it should be -1.0 .
But I can remove such testing.

**Comment by epruesse** [comment]
The files are from a current Thermofisher Quantstudio 7 Pro. I had assumed they'd implemented the standard correctly. Sad.

Perhaps add a lenient/non-strict mode for standard violations that still result in an unambiguous interpretation. In this case, converting NaN to -1.

**Comment by kablag** [comment]
ok. I'll convert NA and NaN to -1.
